#!/usr/bin/env python3
import signal

import rpc
import webui


def start():
    webui_server = webui.serve()
    rpc_server = rpc.serve(webui_server.challenge)
    try:
        while True:
            signal.pause()
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    start()
